/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package it.extrategy.phonemanager;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

import android.content.IntentFilter;
import android.telephony.TelephonyManager;


@Kroll.module(name="Phonemanager", id="it.extrategy.phonemanager")
public class PhonemanagerModule extends KrollModule
{	
	
	@Kroll.method
	public void init() {
		ServiceReceiver receiver =  new ServiceReceiver(this);
		TiApplication.getInstance().getCurrentActivity().registerReceiver(receiver, new IntentFilter(TelephonyManager.ACTION_PHONE_STATE_CHANGED));
	}

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public PhonemanagerModule()
	{
		super();
	}
	
	public void firePhoneStatusChanged(String status) {
		fireEvent("phone_status_change", createEventObject(status));
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
	}
	
	private KrollDict createEventObject (String status) 
	{
		KrollDict event = new KrollDict();
		event.put("status", status);
		return event;
	}
}

